INSERT INTO all_activites (image, titre, nom_lieu, type_lieu, type_architecture, region, adresse, architecte, description, lien_plus, fun_fact) VALUES
('../../assets/uploads/activites/1.jpg', 'Château de Suscinio', 'Château de Suscinio', 'château', 'médiévale', 'Bretagne', 'Route du Duc Jean V, 56370 Sarzeau', 'Jean IV', 'Le château de Suscinio est une impressionnante forteresse médiévale située à Sarzeau dans le Morbihan en Bretagne. Construit aux XIIIe et XIVe siècles comme résidence des ducs de Bretagne, il était particulièrement apprécié pour la chasse. Après avoir servi de carrière de pierres après la Révolution française, le château a été magnifiquement restauré pour retrouver sa splendeur d\'antan. Ses douves, ses tours imposantes et son cadre naturel en font un témoignage exceptionnel de l\'architecture défensive médiévale.', 'https://www.suscinio.fr', 'Le château abrite le fantôme d\'un jeune garçon, fils d\'un capitaine décédé à l\'âge de 5 ans, qui s\'amuse à se signaler aux visiteurs par des bruits et apparitions furtives.'),

('../../assets/uploads/activites/2.jpg', 'Centre Pompidou de Metz', 'Centre Pompidou de Metz', 'Musée d\'art moderne', 'Contemporaine, structure en bois', 'Grand Est', '1 Parvis des Droits de l\'Homme, 57020 Metz', 'Shigeru Ban, Jean de Gastines, Philip Gumuchdjian', 'Le Centre Pompidou-Metz est une annexe du célèbre musée parisien, présentant une architecture audacieuse en forme de chapeau chinois. Son toit ondulant, inspiré par un chapeau de bambou chinois, est une prouesse technique en bois laminé. Le musée offre des espaces d\'exposition modulables et une programmation artistique avant-gardiste, faisant de lui un pôle culturel majeur en région Grand Est.', 'https://www.centrepompidou-metz.fr/', 'La flèche centrale culmine à 77 mètres, référence directe à 1977, année de création du Centre Pompidou à Paris. Par temps clair, on peut apercevoir la cathédrale de Metz depuis le toit-terrasse.'),

('../../assets/uploads/activites/3.jpg', 'Grande Mosquée de Paris', 'Grande Mosquée de Paris', 'Lieu de culte', 'Hispano-mauresque', 'Île-de-France', '2bis Place du Puits de l\'Ermite, 75005 Paris', 'Tranchant de Lunel, Fournez, Mantout, Heubès', 'Édifiée entre 1922 et 1926, la Grande Mosquée de Paris est un joyau architectural hispano-mauresque au cœur de la capitale. Son minaret de 33 mètres domine le quartier latin, tandis que ses jardins andalous, son patio et ses mosaïques zelliges offrent une oasis de tranquillité. La mosquée comprend également un hammam traditionnel et un salon de thé servant des pâtisseries orientales.', 'https://parisjetaime.com/eng/culture/grande-mosquee-de-paris-p3522', 'Pendant la Seconde Guerre mondiale, la mosquée a servi de refuge à des résistants et des Juifs persécutés, leur fournissant des certificats de musulmanité pour les protéger.'),

('../../assets/uploads/activites/4.jpg', 'Mosquée de Fréjus', 'Mosquée de Fréjus', 'Monument historique', 'Inspirée de la mosquée de Djenné', 'PACA', '112 Rue du Malbousquet, 83600 Fréjus', 'Capitaine Mademba', 'La Mosquée Missiri de Fréjus est une réplique en ciment ocre de la célèbre mosquée de Djenné au Mali. Construite en 1930 pour les tirailleurs sénégalais stationnés dans le camp militaire voisin, elle témoigne de l\'histoire coloniale française. Bien que désaffectée religieusement, son architecture sahélo-soudanaise unique en France lui a valu son classement comme monument historique.', 'https://www.frejus.fr/decouvrir/patrimoine-historique/patrimoine-contemporain/mosquee-missiri/', 'Cette mosquée est purement commémorative et n\'a jamais servi au culte - c\'est un hommage architectural aux tirailleurs africains qui ont combattu pour la France.'),

('../../assets/uploads/activites/5.jpg', 'Jardin de Giverny', 'Jardin de Giverny', 'Jardin artistique', 'Japonais et normand', 'Normandie', '84 Rue Claude Monet, 27620 Giverny', 'Claude Monet', 'Immortalisés par les toiles impressionnistes de Claude Monet, les jardins de Giverny sont une œuvre d\'art vivante. Le jardin d\'eau avec son pont japonais et ses nymphéas côtoie le clos normand aux parterres de fleurs savamment désordonnés. Monet y vécut 43 ans, transformant progressivement son environnement en palette végétale changeant au gré des saisons.', 'https://claudemonetgiverny.fr/en/', 'Monet a dû se battre avec les autorités locales pour détourner un bras de l\'Epte et créer son étang aux nymphéas - ces mêmes nymphéas qui deviendront le sujet de ses œuvres les plus célèbres.'),

('../../assets/uploads/activites/6.jpg', 'Jardin Albert Kahn', 'Jardin Albert Kahn', 'Jardin botanique', 'Jardins à thèmes internationaux', 'Île-de-France', '10-14 Rue du Port, 92100 Boulogne-Billancourt', 'Albert Kahn', 'Créé par le banquier philanthrope Albert Kahn, ce jardin extraordinaire rassemble des paysages du monde entier : forêt vosgienne, jardin anglais, forêt bleue, prairie, jardin japonais avec sa maison de thé et son pont rouge, et même une palmeraie. Ces microcosmes végétaux incarnent le rêve de paix universelle d\'Albert Kahn, qui voulait montrer la beauté de chaque culture à travers ses jardins.', 'https://parisjetaume.com/eng/culture/musee-departemental-albert-kahn-p966', 'Albert Kahn a dépensé sa fortune à envoyer des photographes documenter les cultures du monde entier, créant les "Archives de la Planète" - une collection unique de 72.000 autochromes (premiers clichés couleur).'),

('../../assets/uploads/activites/7.jpg', 'Cathédrale de Strasbourg', 'Cathédrale de Strasbourg', 'Cathédrale', 'Gothique', 'Grand Est', 'Place de la Cathédrale, 67000 Strasbourg', 'Erwin von Steinbach', 'Chef-d\'œuvre absolu de l\'art gothique, la cathédrale Notre-Dame de Strasbourg impressionne par sa façade dentelée en grès rose et sa flèche unique culminant à 142 mètres. Elle fut la plus haute construction du monde pendant plus de deux siècles. À l\'intérieur, l\'horloge astronomique Renaissance est un mécanisme d\'une complexité inouïe, mêlant théologie, astronomie et art horloger.', 'https://fr.wikipedia.org/wiki/Cath%C3%A9drale_Notre-Dame_de_Strasbourg', 'La cathédrale possède une horloge astronomique du XVIe siècle dont le mécanisme met en scène un défilé des apôtres chaque jour à 12h30, accompagné d\'un coq doré qui chante et bat des ailes.'),

('../../assets/uploads/activites/8.jpg', 'Jardin André Citroën', 'Jardin André Citroën', 'Parc urbain', 'Contemporaine', 'Île-de-France', 'Quai André Citroën, 75015 Paris', 'Clément, Provost, Berger', 'Aménagé sur l\'ancien site des usines Citroën, ce parc moderne de 14 hectares allie nature et technologie. Ses six jardins thématiques (le jardin en mouvement, le jardin des métamorphoses...) entourent deux grandes serres (une tropicale, une méditerranéenne). La montgolfière captive "Ballon de Paris" offre une vue imprenable à 150 m d\'altitude sur la capitale.', 'https://en.wikipedia.org/wiki/Parc_Andr%C3%A9-Citro%C3%ABn', 'Premier parc parisien entièrement accessible aux personnes à mobilité réduite, il abrite aussi des pelouses où les Parisiens peuvent enfin s\'allonger - une révolution lors de son ouverture en 1992 !'),

('../../assets/uploads/activites/9.jpg', 'Station Arts et Métiers', 'Station Arts et Métiers', 'Station de métro', 'Steampunk/Jules Verne', 'Île-de-France', 'Paris 3e', 'François Schuiten', 'La station Arts et Métiers semble tout droit sortie d\'un roman de Jules Verne : ses parois de cuivre riveté, ses hublots et ses engrenages géants créent l\'illusion d\'être à bord d\'un sous-marin fantastique. Conçue par le dessinateur François Schuiten pour le bicentenaire du Conservatoire National des Arts et Métiers voisin, c\'est un hommage à l\'esprit inventif du XIXe siècle.', 'https://www.ontheluce.com/in-pictures-arts-et-metiers-metro/', 'Les plaques de cuivre ont été volontairement laissées sans vernis protecteur pour qu\'elles s\'oxydent avec le temps, donnant cette patine vieillie typique des machines steampunk.'),

('../../assets/uploads/activites/10.jpg', 'Villa Rothschild', 'Villa Rothschild', 'Villa historique', 'Néo-Renaissance', 'PACA', 'Avenue Denis Semeria, 06230 St-Jean-Cap-Ferrat', 'Aaron Messiah', 'La somptueuse villa Ephrussi de Rothschild, construite par la baronne Béatrice de Rothschild, domine la presqu\'île de Saint-Jean-Cap-Ferrat. Ce palais rose abrite des collections d\'art précieuses (porcelaines, peintures, mobilier) et est entouré de neuf jardins thématiques (à la française, espagnol, florentin, japonais...). Le jardin de pierres offre une vue panoramique sur la Méditerranée.', 'https://www.villa-ephrussi.com/', 'La baronne Rothschild testait ses invités en leur faisant choisir entre deux portes identiques - l\'une menant aux salons, l\'autre à un placard ! Elle adorait ces farces aristocratiques.'),

('../../assets/uploads/activites/11.jpg', 'Château de Versailles', 'Château de Versailles', 'Château royal', 'Baroque classique', 'Île-de-France', 'Place d\'Armes, 78000 Versailles', 'Le Vau, Mansart', 'Symbole absolu de la monarchie française, le château de Versailles fut la résidence du Roi-Soleil Louis XIV. Ses galeries dorées, ses appartements royaux et surtout la galerie des Glaces (73 m de long avec 357 miroirs) éblouissent par leur faste. Les jardins à la française de Le Nôtre, avec leurs bosquets, fontaines et le Grand Canal, forment un écrin de perfection géométrique.', 'https://www.chateauversailles.fr/', 'Classé au patrimoine mondial de l\'UNESCO depuis 1979, le domaine compte 2.300 pièces, 67 escaliers, 352 cheminées et 2.143 fenêtres. Les jardins nécessitaient 1.500 fontainiers rien que pour faire fonctionner les jeux d\'eau lors des fêtes royales !'),

('../../assets/uploads/activites/12.jpg', 'Jardin de Vincennes', 'Jardin de Vincennes', 'Parc urbain', 'Paysager', 'Île-de-France', 'Route de la Pyramide, 75012 Paris', 'Collectif de paysagistes', 'Le bois de Vincennes, poumon vert de l\'est parisien, s\'étend sur près de 995 hectares - soit près de 10% de la surface de Paris intra-muros ! On y trouve le parc floral avec ses milliers d\'espèces, le zoo historique de Vincennes rénové, quatre lacs, un hippodrome et même un temple bouddhiste. Ce parc offre une échappée naturelle aux Parisiens depuis le Second Empire.', 'https://www.paris.fr/equipements/bois-de-vincennes-1758', 'Le zoo de Vincennes hébergeait autrefois un éléphant nommé Bouglione, offert par la célèbre famille de cirque. Aujourd\'hui, ses nouveaux pensionnaires évoluent dans un "bio-parc" reproduisant leurs habitats naturels.'),

('../../assets/uploads/activites/13.jpg', 'Palais Idéal du Facteur Cheval', 'Palais Idéal du Facteur Cheval', 'Palais fantastique', 'Art naïf', 'Auvergne-Rhône-Alpes', '8 Rue du Palais, 26390 Hauterives', 'Ferdinand Cheval', 'Ce palais onirique est l\'œuvre d\'un seul homme : Ferdinand Cheval, facteur rural qui consacra 33 ans de sa vie (1879-1912) à bâtir ce monument éclectique. Sans formation architecturale, il créa une structure mêlant inspirations hindoues, médiévales et naturelles, assemblant pierres ramassées lors de ses tournées. André Malraux le classa monument historique en 1969 comme unique exemple d\'architecture naïve.', 'https://www.facteurcheval.com/', 'Ferdinand Cheval a ramassé toutes les pierres pendant ses tournées de facteur (environ 30 km par jour), les transportant d\'abord dans ses poches, puis avec une brouette. Il a écrit sur son palais : "1879-1912 : 10.000 journées, 93.000 heures, 33 ans d\'épreuves."'),

('../../assets/uploads/activites/14.jpg', 'La Cité du Vin', 'La Cité du Vin', 'Musée', 'Contemporaine organique', 'Nouvelle-Aquitaine', '134 Quai de Bacalan, 33300 Bordeaux', 'XTU Architects', 'La Cité du Vin est bien plus qu\'un musée : c\'est une expérience sensorielle totale dédiée au vin à travers les âges et les continents. Son architecture audacieuse évoque les mouvements d\'un vin qu\'on fait tourner dans un verre. À l\'intérieur, des installations interactives, des dégustations et même un parcours olfactif invitent à découvrir toutes les dimensions de la culture viticole mondiale.', 'https://www.laciteduvin.com', 'Le bâtiment change de couleur selon la lumière du jour grâce à ses 3.000 panneaux métalliques irisés. Au sommet du belvédère (35m), le bar offre une vue à 360° sur Bordeaux et ses vignobles, avec des vins du monde entier à déguster.'),

('../../assets/uploads/activites/15.jpg', 'Louvre-Lens', 'Louvre-Lens', 'Musée', 'Minimalisme contemporain', 'Hauts-de-France', '99 Rue Paul Bert, 62300 Lens', 'SANAA (Kazuyo Sejima et Ryue Nishizawa)', 'Le Louvre-Lens est une annexe décentralisée du musée parisien, installée dans un bâtiment épuré de verre et d\'aluminium qui semble flotter sur le paysage. Conçu par l\'agence japonaise SANAA, son architecture fluide sans angles droits crée une sensation de continuité entre les espaces. La Galerie du Temps présente 200 œuvres du Louvre dans un accrochage chronologique révolutionnaire.', 'https://www.louvrelens.fr', 'Les murs du musée sont volontairement sans angles droits pour créer un effet de fluidité. Le bâtiment s\'intègre dans un parc de 20 hectares aménagé sur d\'anciennes fosses minières, symbole de la reconversion du bassin minier.'),

('../../assets/uploads/activites/16.jpg', 'Mucem', 'Mucem', 'Musée', 'Contemporaine en béton dentelle', 'PACA', '7 Prom. Robert Laffont, 13002 Marseille', 'Rudy Ricciotti et Roland Carta', 'Le Musée des civilisations de l\'Europe et de la Méditerranée est une prouesse architecturale : sa résille de béton fibré ultra-fin (8 cm d\'épaisseur seulement) forme une dentelle minérale qui filtre la lumière. Situé à l\'entrée du Vieux-Port, il est relié au fort Saint-Jean par une passerelle spectaculaire. Ses collections explorent les cultures méditerranéennes à travers objets du quotidien et œuvres d\'art.', 'https://www.mucem.org', 'Le béton spécial du Mucem contient des fibres de verre et est si fin qu\'il laisse passer la lumière comme une résille végétale. Par temps ensoleillé, le musée projette une ombre ajourée qui danse sur les quais.'),

('../../assets/uploads/activites/17.jpg', 'Jardin du Château de Maintenon', 'Jardin du Château de Maintenon', 'Jardin à la française', 'Classique', 'Centre-Val de Loire', '28130 Maintenon', 'Non spécifié', 'Les jardins du château de Maintenon, dessinés pour Madame de Maintenon (épouse secrète de Louis XIV), offrent une magnifique perspective à la française. L\'allée centrale aligne parfaitement le château, les jardins et les vestiges de l\'aqueduc inachevé de Vauban. Ce dernier devait alimenter les fontaines de Versailles mais le projet fut abandonné après la mort de Colbert. Les parterres de buis et les miroirs d\'eau reflètent l\'élégance du Grand Siècle.', 'chateaudemaintenon.fr', 'L\'aqueduc inachevé qui traverse le domaine témoigne des ambitions hydrauliques de l\'époque : Vauban voulait amener l\'eau de l\'Eure jusqu\'à Versailles sur 80 km ! Seul un tiers fut construit avant l\'abandon du projet pharaonique.'),

('../../assets/uploads/activites/18.jpg', 'Parc du Château de Chaumont-sur-Loire', 'Parc du Château de Chaumont-sur-Loire', 'Parc et château', 'Médiévale et Renaissance', 'Centre-Val de Loire', '41150 Chaumont-sur-Loire', 'Henri Duchêne', 'Dominant la Loire, le domaine de Chaumont-sur-Loire allie un château médiéval remanié à la Renaissance et des jardins exceptionnels. Le Festival International des Jardins, organisé chaque année depuis 1992, en fait un laboratoire du paysagisme contemporain. Le parc historique offre quant à lui des vues spectaculaires sur le fleuve et abrite des écuries somptueuses bâties pour la princesse de Broglie.', 'https://domaine-chaumont.fr/fr/informations-pratiques', 'Le château a appartenu à Catherine de Médicis qui, selon la légende, y fit pratiquer des séances de magie par son astrologue Ruggieri. Elle l\'échangea contre Chenonceau après la mort de son époux Henri II.'),

('../../assets/uploads/activites/19.jpg', 'Parc de la Colline aux Oiseaux', 'Parc de la Colline aux Oiseaux', 'Parc paysager', 'Paysagère contemporaine', 'Normandie', 'Avenue Amiral Mountbatten, 14000 Caen', 'Non spécifié', 'Aménagé sur une ancienne décharge municipale, la Colline aux Oiseaux est devenue un écrin de verdure de 17 hectares. Inauguré pour le 50e anniversaire du Débarquement, ce parc propose une roseraie de 15.000 plants, un jardin de senteurs, un labyrinthe végétal et même une mini-ferme. Son nom vient des nombreux oiseaux attirés par ce havre de paix en plein Caen.', 'https://caen.fr/annuaire-equipement/colline-aux-oiseaux', 'Ce parc est une véritable renaissance écologique : il a transformé une décharge à ciel ouvert (qui recevait les déblais de la reconstruction après 1944) en un oasis de biodiversité fréquenté par 80 espèces d\'oiseaux.'),

('../../assets/uploads/activites/20.jpg', 'Jardin des Plantes à Paris', 'Jardin des Plantes à Paris', 'Jardin botanique', 'Classique et Art déco', 'Île-de-France', '57 Rue Cuvier, 75005 Paris', 'René Berger', 'Fondé en 1626 comme jardin royal des plantes médicinales, le Jardin des Plantes est le cœur historique du Muséum national d\'Histoire naturelle. Ses allées bordées de platanes bicentenaires mènent aux grandes serres Art déco, à la ménagerie (2e zoo le plus ancien du monde) et aux galeries scientifiques. Les carrés de la perspective présentent 4.500 espèces végétales selon une classification toujours actualisée.', 'https://www.jardindesplantesdeparis.fr/en', 'Pendant le siège de Paris en 1870, les animaux du zoo furent mangés par les Parisiens affamés, y compris les deux éléphants Castor et Pollux, vendus aux enchères pour 27.000 francs or de l\'époque.'),

('../../assets/uploads/activites/21.jpg', 'Jardin Japonais de Toulouse', 'Jardin Japonais de Toulouse', 'Jardin japonais', 'Inspirée de Katsura, Kyoto', 'Occitanie', 'Jardin Compans-Caffarelli, 31000 Toulouse', 'Services municipaux', 'Ce havre de paix en plein Toulouse reproduit les éléments essentiels des jardins japonais : pont rouge laqué, pavillon de thé, lanternes de pierre, cours d\'eau sinueux et végétation soigneusement choisie (érables, cerisiers, pins taillés). Conçu par des paysagistes nippons, il suit les principes du shin-gyo-so (formel, semi-formel, informel) pour évoquer différents paysages en miniature.', 'https://www.toulouse-tourisme.com/activite/jardin-japonais/', 'Tous les éléments du jardin ont une signification symbolique : le pont rouge représente le passage vers le paradis, les pierres disposées en triangle évoquent Bouddha entouré de disciples, et les cerisiers rappellent l\'éphémère beauté de la vie.'),

('../../assets/uploads/activites/22.jpg', 'Jardin Secret Vaulx', 'Jardin Secret Vaulx', 'Jardin privé', 'Éclectique orientale', 'Auvergne-Rhône-Alpes', '1561 Route de Lagnat, 74150 Vaulx', 'Famille Moumen', 'Sur 7.000 m², les Jardins Secrets de Vaulx transportent le visiteur dans un univers onirique mêlant influences marocaines, andalouses et asiatiques. Créés par la famille Moumen, ces jardins labyrinthiques cachent des patios, des bassins, des bois sculptés et des constructions insolites. Chaque recoin raconte une histoire inspirée des voyages des propriétaires, dans une explosion de couleurs et de parfums.', 'https://www.jardins-secrets.com/', 'Les propriétaires ont sculpté eux-mêmes tous les éléments décoratifs en bois durant 20 ans, sans plan préétabli, suivant simplement leur inspiration du moment - ce qui donne au jardin son caractère organique unique.'),

('../../assets/uploads/activites/23.jpg', 'Jardin de la Violette', 'Jardin de la Violette', 'Jardin thématique', 'Contemporaine', 'Auvergne-Rhône-Alpes', '69120 Vaulx-en-Velin', 'Non spécifié', 'Dédié à la violette, fleur emblématique de la région lyonnaise, ce jardin sensoriel permet de découvrir toutes les variétés de cette plante modeste mais parfumée. Des ateliers enseignent comment confectionner bonbons, parfums et liqueurs à la violette, spécialités locales depuis le XIXe siècle. Le parcours olfactif guide les visiteurs à travers les différentes utilisations de cette fleur dans la gastronomie et la parfumerie.', 'Non disponible', 'La violette de Toulouse a failli disparaître dans les années 1950 - sauvée par un seul horticulteur, elle connaît aujourd\'hui un renouveau. On peut fabriquer son propre parfum à la violette lors d\'ateliers dans le jardin.'),

('../../assets/uploads/activites/24.jpg', 'Jardin Buttes Chaumont', 'Jardin Buttes Chaumont', 'Parc urbain', 'Paysagère haussmannienne', 'Île-de-France', '75019 Paris', 'Jean-Charles Alphand', 'Avec ses falaises abruptes, son lac, sa grotte à stalactites et son pont suspendu, le parc des Buttes-Chaumont semble un paysage naturel... mais tout y est artificiel ! Créé sous Haussmann sur d\'anciennes carrières de gypse et une décharge publique, ce parc de 25 hectares est un chef-d\'œuvre d\'ingénierie paysagère. Le temple de la Sibylle, perché à 50 m de haut, offre une vue panoramique sur Paris.', 'https://www.paris.fr/equipements/parc-des-buttes-chaumont-1741', 'Le parc a été construit sur un site si insalubre (carrières, égouts à ciel ouvert, gibet de Montfaucon) qu\'on l\'appelait "le champ du diable". Les 200.000 m³ de terre fertile furent apportés par charrettes depuis la plaine de Gennevilliers.'),

('../../assets/uploads/activites/25.jpg', 'Mont Saint-Michel', 'Mont Saint-Michel', 'Site historique', 'Roman / gothique', 'Normandie', '50170 Pontorson', 'Benoît de Saint-Michel', 'Émergeant des sables et des marées, le Mont-Saint-Michel est un prodige d\'architecture médiévale. Son abbaye bénédictine, construite entre le XIe et le XVIe siècle, se dresse à 80 mètres au-dessus de la baie. Le village fortifié qui l\'entoure et les remparts ajoutent à son caractère de citadelle céleste. Les phénomènes de marées (jusqu\'à 14 m de marnage) en font un spectacle naturel changeant au rythme des heures.', 'https://www.ot-montsaintmichel.com/', 'Le Mont peut être entouré par la mer lors des grandes marées (coefficient supérieur à 110), mais contrairement à la légende, il ne devient pas une île - la route submersible reste praticable. Les pèlerins médiévaux appelaient ce phénomène "la marche dans le ciel".'),

('../../assets/uploads/activites/26.jpg', 'Sainte-Chapelle', 'Sainte-Chapelle', 'Chapelle royale', 'Gothique rayonnant', 'Île-de-France', '75001 Paris', 'Pierre de Montreuil', 'Joyau du gothique rayonnant, la Sainte-Chapelle fut édifiée en seulement 7 ans (1242-1248) pour abriter les reliques de la Passion acquises par Saint Louis. Son architecture audacieuse, avec ses vitraux hauts de 15 mètres couvrant 600 m², crée une "châsse de lumière". Les 1.113 scènes bibliques des vitraux forment une véritable Bible en images destinée aux fidèles médiévaux, majoritairement illettrés.', 'https://www.sainte-chapelle.fr/', 'Quand le soleil traverse les vitraux, toute la chapelle haute se pare de reflets colorés qui dansent sur les murs et le sol - un effet voulu par les bâtisseurs pour créer une "Jérusalem céleste" sur terre. Les vitraux ont été démontés et cachés pendant les deux guerres mondiales pour les protéger.'),

('../../assets/uploads/activites/27.jpg', 'Abbaye de Sénanque', 'Abbaye de Sénanque', 'Abbaye cistercienne', 'Roman cistercien', 'Provence-Alpes-Côte d\'Azur', '84220 Gordes', 'Moines cisterciens du XIIe siècle', 'Encerclée par des champs de lavande, l\'abbaye de Sénanque est un pur exemple d\'architecture cistercienne du XIIe siècle, sobre et harmonieuse. Toujours habitée par une communauté de moines, elle conserve son cloître roman, son église aux lignes épurées et son scriptorium où les moines copiaient les manuscrits. La lavande cultivée par les moines est distillée pour produire huiles essentielles et miel parfumé.', 'https://www.senanque.fr/', 'Les moines suivent toujours la règle de saint Benoît ("ora et labora" - prie et travaille) et vivent en autarcie presque complète. Leur journée commence à 4h du matin par les matines, et ils observent le silence la plupart du temps.'),

('../../assets/uploads/activites/28.jpg', 'Cathédrale de Chartres', 'Cathédrale de Chartres', 'Cathédrale', 'Gothique', 'Centre-Val de Loire', '28000 Chartres', 'Jean Texier, dit Jean de Beauce', 'Considérée comme le chef-d\'œuvre absolu de l\'art gothique, la cathédrale de Chartres éblouit par ses 176 vitraux médiévaux (dont le célèbre "Bleu de Chartres") et son labyrinthe de 261 m de long au sol. Sa façade occidentale conserve un portail royal roman sculpté, tandis que les flèches asymétriques (113m et 105m) dominent la Beauce. Les pèlerins y vénèrent la "Vierge qui va enfanter", statue du XIIe siècle.', 'https://www.cathedrale-chartres.org/', 'La cathédrale possède un vitrail montrant la Vierge Marie allaitant l\'enfant Jésus - une représentation rare appelée "Virgo Lactans". Son labyrinthe servait aux pèlerins qui ne pouvaient aller à Jérusalem : ils le parcouraient à genoux comme substitut symbolique du pèlerinage.'),

('../../assets/uploads/activites/29.jpg', 'Hospices de Beaune', 'Hospices de Beaune', 'Ancien hôpital/musée', 'Gothique', 'Bourgogne-Franche-Comté', '21200 Beaune', 'Jacques Wiscrère', 'Les Hospices de Beaune, fondés en 1443 comme hôpital pour les pauvres, sont célèbres pour leur toiture polychrome vernissée formant des motifs géométriques. La grande salle des "Pôvres", longue de 50 m, abritait les lits des malades sous son plafond en forme de coque de bateau renversée. Aujourd\'hui musée, l\'institution perpétue sa mission caritative par la vente aux enchères de vins de son prestigieux domaine.', 'https://hospices-de-beaune.com/', 'Chaque troisième dimanche de novembre, la vente aux enchères des vins des Hospices (dont le célèbre "Pièce des Présidents") rassemble les grands noms de la viticulture mondiale. Les bénéfices financent toujours l\'hôpital moderne de Beaune.'),

('../../assets/uploads/activites/30.jpg', 'Cathédrale de Metz', 'Cathédrale de Metz', 'Cathédrale', 'Gothique', 'Grand Est', '57000 Metz', 'Pierre Perrat', 'Surnommée la "Lanterne du Bon Dieu" pour ses 6.500 m² de vitraux (la plus grande surface vitrée de France), la cathédrale Saint-Étienne de Metz mêle styles gothiques du XIIIe au XXe siècle. Ses verrières incluent des chefs-d\'œuvre de Marc Chagall et Jacques Villon. La nef, haute de 42 m, est l\'une des plus élevées de France, et son portail du XIVe siècle présente un rare Jugement dernier où le Christ sourit.', 'https://www.cathedrale-metz.fr/', 'Les vitraux de Chagall, réalisés entre 1958 et 1968, sont reconnaissables à leurs bleus profonds et à leurs motifs bibliques. Par temps ensoleillé, la cathédrale se transforme en véritable kaléidoscope de lumière colorée.'),

('../../assets/uploads/activites/31.jpg', 'Mosquée de Strasbourg', 'Mosquée de Strasbourg', 'Mosquée', 'Islamique moderne', 'Grand Est', '67100 Strasbourg', 'Paolo Portoghesi', 'Plus grande mosquée de France (5.000 m²), l\'édifice se distingue par son dôme vert et son minaret de 24 mètres. Conçue par l\'architecte italien Paolo Portoghesi, elle mêle tradition islamique et modernité, avec une grande salle de prière ornée de calligraphies et une coupole évoquant une fleur ouverte. Le centre culturel attenant comprend une bibliothèque spécialisée dans les études islamiques et un restaurant halal.', 'https://grande-mosquee-strasbourg.com/', 'La mosquée possède une collection unique de 30.000 ouvrages sur l\'islam et le dialogue interreligieux, dont des manuscrits anciens. Son architecture symbolise l\'"arbre de vie" avec 72 colonnes représentant les branches.'),


ALTER TABLE all_activites ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY FIRST;


CREATE TABLE activite_quizz (
  id INT PRIMARY KEY AUTO_INCREMENT,
  activite_id INT NOT NULL,
  
  -- Question 1 et ses choix
  question_1 VARCHAR(255) NOT NULL,
  q1_choix_1 VARCHAR(100) NOT NULL,
  q1_choix_2 VARCHAR(100) NOT NULL,
  q1_choix_3 VARCHAR(100) NOT NULL,
  q1_choix_4 VARCHAR(100) NOT NULL,
  reponse_1 VARCHAR(100) NOT NULL,
  
  -- Question 2 et ses choix
  question_2 VARCHAR(255) NOT NULL,
  q2_choix_1 VARCHAR(100) NOT NULL,
  q2_choix_2 VARCHAR(100) NOT NULL,
  q2_choix_3 VARCHAR(100) NOT NULL,
  q2_choix_4 VARCHAR(100) NOT NULL,
  reponse_2 VARCHAR(100) NOT NULL,
  
  -- Question 3 et ses choix
  question_3 VARCHAR(255) NOT NULL,
  q3_choix_1 VARCHAR(100) NOT NULL,
  q3_choix_2 VARCHAR(100) NOT NULL,
  q3_choix_3 VARCHAR(100) NOT NULL,
  q3_choix_4 VARCHAR(100) NOT NULL,
  reponse_3 VARCHAR(100) NOT NULL,
  
  FOREIGN KEY (activite_id) REFERENCES all_activites(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;